#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-HiLiter
version:      0.08
version_from: HiLiter.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
