---
abstract: 'highlight words in an HTML document just like a felt-tip HiLiter'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-HiLiter
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  File::Slurp: '0'
  HTML::Parser: '0'
  Moose: '0'
  Search::Tools: '1.000'
  Test::More: '0'
  perl: '5.008003'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTML-HiLiter
  homepage: http://perl.peknet.com/wiki/HTMLHiLiter
  license: http://dev.perl.org/licenses/
  repository: http://svn.peknet.com/perl/HTML-HiLiter
version: '0.200'
