--- #YAML:1.0
name:               HTML-HiLiter
version:            0.14
abstract:           highlight words in an HTML document just like a felt-tip HiLiter
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:     0
    File::Slurp:    0
    HTML::Parser:   0
    perl:           5.008003
    Rose::Object:   0
    Search::Tools:  0.26
    Test::More:     0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTML-HiLiter
    homepage:    http://perl.peknet.com/wiki/HTMLHiLiter
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.peknet.com/perl/HTML-HiLiter
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
